language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- 3.6-dev
- 3.7-dev
install:
- pip install --upgrade pip
- pip install .[test]
script:
- nosetests
deploy:
  provider: pypi
  user: grantstephens
  password:
    secure: rLx4cnXdnAGiloflh6uY6VniJOxgQyhfi/iULpowgsFWkDiQ20ufSl5GEuRvPLvYHWeeqezLGwZTSUZ5lN582N9mFFQkkgsxL0gt6/d3T3bINZaiMvnQT+5KE8GhGURUHwaZR7ycIbz0v1lDvC7JA2TUVH2yACgrVUQA1YiAEsVfLXHDvJLHRUvhX9dCRDgZv6XXerg4xkyrjwRfFpgzetC2xN6DGrfr8KDzeLooFRTN2MkkYNJhfvhHowv+h9eHHmq7R4oBsrE1jJypdgWS2uFK6ALJf6EovauLsQY2huVwFbkBk9D3OraQ3Wnw9K7g21YnJRrgnabaUDZYfb5Oz8nXc6pV+1C7AJlvtbxJQIa3h6/zpDFu377HiVWj7/uwHSpMmySHIuqDfIOS010ofwNmV8ColvcFJpkP0J0Tigt+7pL6SbxdtOBbKenrUGF9VhjupWGvl3gpRgLGLaS6Z1Qm3k3PkiNpKG0pEGvBbG/85pFFOVB6BYaFojQPsJy0j3f5Resw1w7jC/bB5D2kwEenpyQ3M/r81/tna6/sJ0W7snckmdAW8Qhp4GLxkfMIWLr8oFEtQ2MZT6SYGmSeZ28sWdTaRKvj5Mvang4rHUspPu9flwU34x8JLc/LU6GufAV8OWG+Pj61IS1jFlsaVy8lkWBIMvHLXcLsvaUuz3I=
  on:
    tags: true
    branch: master
  distributions: sdist bdist_wheel
notifications:
  email: false
